modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"

[[mods]]

modId = "${mod_id}"
version = "1.0"
displayName = "Alpha Test"
logoFile="alpha_test.png"
updateJSONURL = "https://discord.gg/ZtK3DjTZF4"

description = '''Authors: §bLinnett§r

Mod about new stranje and interesting aeyjetics: Cleancore, Webcore, Frutiger aero...

'''


[[dependencies."${mod_id}"]]

modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]

modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
